### ISSUE TITLE
Previous match QR codes contain only event 1

### ISSUE THREAD

**Issue by MangoSwirl** [HighlanderRobotics/Collection-App-2023#6]

**Comment by MangoSwirl** [comment]
All QR codes have this, and some but not all saved files have this.

**Comment by MangoSwirl** [comment]
`MatchData.fromJson()` seems to be where the events are replaced

**Comment by MangoSwirl** [comment]
Source found:

`event.dart` line 14:
```dart
factory Event.fromJson(List<dynamic> json) {
  return Event(
    timeSince: Duration(seconds: json[0]),
    action: RobotAction.values[1], // Always event 1, ignores JSON
    position: json[2],
  );
}
```

**Comment by MangoSwirl** [comment]
I've created a fix. It doesn't solve the files being wrong, but that might be the intended behavior and I just forgot the data I entered. I'll do some additional testing.

**Comment by MangoSwirl** [comment]
As far as I can tell, the saved file being only 1s was because in my testing I genuinely only recorded the robot as picking up a cone. #8 should be ready to merge.

**Comment by Awesomeplayer165** [comment]
Thank you for this @MangoSwirl. lgtm
